version: '3'

volumes:
  database2: {}

services:
  # Named "database2" because "database" conflicts with directory inside project
  database2:
    image: mysql:8
    environment:
      MYSQL_DATABASE: budget
      MYSQL_USER: budget
      MYSQL_PASSWORD: test
      MYSQL_RANDOM_ROOT_PASSWORD: 'true'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - database2:/var/lib/mysql

  php:
    build: ./
    ports:
      - 8080:80
    env_file:
    - .env
    environment:
      DB_HOST: database2
      DB_DATABASE: budget
      DB_USERNAME: budget
      DB_PASSWORD: test
